Repository LunarStation/Lunar-Station-13, pull requests merged in 2021-08, with the labels that each got.

#201 [MIRROR] Random Boxstation Fixes (Space edition)
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Upstream PR Merged

#200 [MIRROR] Pubby Deco
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Upstream PR Merged

#199 [MIRROR] [Review/Testmerge] Icemoon Ruins but on Lavaland!
  _maps/RandomRuins/LavaRuins/lavaland_surface_bathhouse.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_engioutpost.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hotsprings.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_library.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_lust.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_mining_site.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_wrath.dmm
  code/datums/ruins/lavaland.dm
Labels: Upstream PR Merged

#198 [MIRROR] Round 1 of initial fixes/changes for OmegaStation.
  _maps/map_files/OmegaStation/OmegaStation.dmm
  tgstation.dme
Labels: Upstream PR Merged

#203 [MIRROR] [READY] tempgun rebalance (it's not a nerf don't worry)
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special/temperature.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  sound/weapons/frost.ogg
Labels: Upstream PR Merged

#204 [MIRROR] Fixes brainless sprite being an error sprite
  code/modules/mob/living/carbon/human/species.dm
Labels: Upstream PR Merged

#205 [MIRROR] [TESTMERGE FIRST HOLY SHIT FUCK] fixes every single leg sprite in the entire game
  code/modules/surgery/bodyparts/_bodyparts.dm
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/mob/legfile1test.dmi
  icons/mob/legfile2test.dmi
Labels: Upstream PR Merged

#207 [MIRROR] makes organs decay again
  code/modules/surgery/organs/organ_internal.dm
Labels: Upstream PR Merged

#209 [MIRROR] Fixes certain skirty uniforms not having the FEMALE_UNIFORM_TOP fitted flag
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Upstream PR Merged

#212 [MIRROR] Halves probability on supernova rads
  code/modules/events/supernova.dm
Labels: Upstream PR Merged

#214 [MIRROR] Adds military gas mask for donator
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Upstream PR Merged

#216 [MIRROR] Old Gateway animation return
  code/modules/awaymissions/gateway.dm
  icons/obj/machines/gateway.dmi
Labels: Upstream PR Merged

#215 [MIRROR] Makes rod of asclepius usable for revival surgery
  code/modules/surgery/advanced/revival.dm
Labels: Upstream PR Merged

#217 Sync
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/turfs/simulated/water.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: Code Improvement, Map Edit

#219 [MIRROR] lets felinids, humans and moths have markings
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
Labels: Upstream PR Merged, Feature

#220 [MIRROR] Automatically fails pull requests with broken line endings
  tools/ci/check_grep.sh
Labels: Upstream PR Merged, Tools

#218 Add autocloner
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/autoclone_lr.dm
  code/game/machinery/cloning_lr.dm
  code/modules/mob/living/carbon/human/death_lr.dm
  tgstation.dme
Labels: Feature

#221 [MIRROR] Makes supermatter properties auxgm-based
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Upstream PR Merged, Refactor

#223 [MIRROR] Reworks blood regeneration into something a bit more tame
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/abductor/equipment/glands/heal.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/alien/organs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/xenobiology/crossbreeding/consuming.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/organs/lungs.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
Labels: Upstream PR Merged, Removal

#225 [MIRROR] Changelings now use a radial menu to select DNAs (tg port)
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/humanform.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/changeling/powers/transform.dm
  icons/mob/radial.dmi
Labels: Upstream PR Merged, Sprites

#226 [MIRROR] Admin buildmode repair block now fixes baseturfs instead of simply placing plasteel flooring on empty space
  code/modules/procedural_mapping/mapGenerators/repair.dm
Labels: Upstream PR Merged

#228 [MIRROR] Polyvitiligo now actually does something instead of making you a crayon eater.
  code/datums/brain_damage/severe.dm
  code/datums/diseases/advance/symptoms/skin.dm
  html/changelog.html
  html/changelogs/AutoChangeLog-pr-224.yml
Labels: Upstream PR Merged, Fix

#229 [MIRROR] lets you select 4 prosthetic limbs instead of only 2
  code/__DEFINES/loadout.dm
Labels: Upstream PR Merged, Feature

#234 [MIRROR] Adds some showers to the beach
  _maps/RandomZLevels/away_mission/TheBeach.dmm
Labels: Upstream PR Merged, Map Edit, Feature

#233 [MIRROR] Pubby Additions + Touchups
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Upstream PR Merged, Map Edit, Feature, Fix

#232 [MIRROR] [Ready] Blank Bottles
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/nodes/export_nodes.dm
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Upstream PR Merged, Sprites, Feature

#231 [MIRROR] Ship happens on OmegaStation.
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Upstream PR Merged, Map Edit, Feature, Removal

#230 [MIRROR] [Ready] Shark Tails, dodododododo
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Upstream PR Merged, Sprites, Feature

#235 [MIRROR] undoes a small amount of Trillby™ Spelling™
  code/datums/components/crafting/glassware/lens_crafting.dm
Labels: Upstream PR Merged, Grammar and Formatting

#236 [MIRROR] Old Gateway animation return: now includes less icons
  code/modules/awaymissions/gateway.dm
  icons/obj/machines/gateway.dmi
Labels: Upstream PR Merged, Sprites

#237 [MIRROR] undoes more Trillby™ Spelling™
  code/datums/components/crafting/glassware/glassware.dm
Labels: Upstream PR Merged, Grammar and Formatting

#238 [MIRROR] Brings back the MK ultra gas, remove MK ultra explosion, but makes the gas less horny and prefbreaky
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Upstream PR Merged, Balance/Rebalance

#255 [MIRROR] Fixes waddling ruining character size and forcing character scale to 1
  code/datums/components/waddling.dm
Labels: Upstream PR Merged, Fix

#254 [MIRROR] Fixes updates for rechargers & energy guns, ports "recharge feedback" from TG
  code/game/machinery/recharger.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  icons/obj/stationobjs.dmi
Labels: Upstream PR Merged, Sprites, Feature, Fix

#253 [MIRROR] fixes the chainsaw sprite
  icons/mob/inhands/weapons/chainsaw_lefthand.dmi
  icons/mob/inhands/weapons/chainsaw_righthand.dmi
Labels: Upstream PR Merged
